# Generated by Django 4.1.4 on 2023-05-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='created',
        ),
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='updated',
        ),
        migrations.CreateModel(
            name='MaticnaSekcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('maticnaSekcija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.regionalnicentar')),
            ],
        ),
    ]
