# Generated by Django 4.1.4 on 2023-05-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_maticnasekcija_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maticnasekcija',
            old_name='maticnaSekcija',
            new_name='regionalnicentar',
        ),
    ]
