# Generated by Django 4.1.4 on 2023-05-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_regionalnicentar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maticnasekcija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maticnasekcija')),
            ],
        ),
    ]
