# Generated by Django 4.1.4 on 2023-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.CharField(max_length=50),
        ),
    ]
