# Generated by Django 4.1.4 on 2023-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_customer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='kandidati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
