# Generated by Django 4.1.4 on 2023-05-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_kandidati_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidati',
            name='maticnasekcija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maticnasekcija'),
        ),
        migrations.AddField(
            model_name='kandidati',
            name='regionalnicentar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.regionalnicentar'),
        ),
        migrations.AlterField(
            model_name='kandidati',
            name='ime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kandidati',
            name='prezime',
            field=models.CharField(max_length=100),
        ),
    ]
