# Generated by Django 4.1.4 on 2023-05-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_kandidati_maticnasekcija_kandidati_regionalnicentar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kandidati',
        ),
    ]
