# Generated by Django 4.1.4 on 2023-05-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_kandidati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidati',
            name='name',
        ),
    ]
