# Generated by Django 4.1.4 on 2023-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_kandidati_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kandidati',
        ),
    ]
