# Generated by Django 4.1.4 on 2023-05-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_kandidati'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('maticna_sekcija', models.CharField(max_length=100)),
                ('regionalni_centar', models.CharField(max_length=100)),
                ('maticnasekcija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maticnasekcija')),
                ('regionalnicentar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.regionalnicentar')),
            ],
        ),
    ]
