# Generated by Django 4.1.4 on 2023-05-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_myuser_maticnasekcija_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidati',
            name='user',
        ),
    ]
