# Generated by Django 4.1.4 on 2023-05-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_regionalnicentar_maticnasekcija_izbornakomisija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maticnasekcija',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='name',
        ),
    ]
