# Generated by Django 4.1.4 on 2023-05-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_maticnasekcija_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izbornakomisija',
            name='maticnasekcija',
        ),
    ]
