# Generated by Django 4.1.4 on 2023-05-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_izbornakomisija_maticnasekcija'),
    ]

    operations = [
        migrations.AddField(
            model_name='izbornakomisija',
            name='maticnasekcija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maticnasekcija'),
        ),
    ]
