# Generated by Django 4.1.4 on 2023-05-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_izbornakomisija_maticnasekcija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izbornakomisija',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maticnasekcija',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='user',
        ),
    ]
