# Generated by Django 4.1.4 on 2023-05-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_regionalnicentar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izbornakomisija',
            name='maticnasekcija',
        ),
        migrations.RemoveField(
            model_name='izbornakomisija',
            name='regionalnicentar',
        ),
        migrations.RemoveField(
            model_name='regionalnicentar',
            name='user',
        ),
        migrations.AddField(
            model_name='regionalnicentar',
            name='userizbornakomisija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.izbornakomisija'),
        ),
    ]
