# Generated by Django 4.1.4 on 2023-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_userizbornakomisija_regionalnicentar_izbornakomisija'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalnicentar',
            name='broj',
            field=models.IntegerField(default=0),
        ),
    ]
