# Generated by Django 4.1.4 on 2023-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_regionalnicentar_broj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='izbornakomisija',
            options={'verbose_name_plural': 'Izborna Komisija'},
        ),
        migrations.AlterModelOptions(
            name='kandidati',
            options={'verbose_name_plural': 'Kandidati'},
        ),
        migrations.AlterModelOptions(
            name='maticnasekcija',
            options={'verbose_name_plural': 'Maticna Sekcija'},
        ),
        migrations.AlterModelOptions(
            name='regionalnicentar',
            options={'verbose_name_plural': 'Regionalni Centri'},
        ),
        migrations.AlterField(
            model_name='kandidati',
            name='maticna_sekcija',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kandidati',
            name='regionalni_centar',
            field=models.IntegerField(default=0),
        ),
    ]
