# Generated by Django 4.1.4 on 2023-05-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_izbornakomisija_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidati',
            name='maticna_sekcija',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kandidati',
            name='regionalni_centar',
            field=models.CharField(max_length=100),
        ),
    ]
