# Generated by Django 4.2.1 on 2023-06-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0002_remove_ballot_voter_remove_historicalballot_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Process.election'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Historicalballot',
        ),
    ]
