# Generated by Django 4.1.4 on 2023-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sifra',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
