# Generated by Django 4.1.4 on 2023-06-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0003_customuser_sifra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sifra',
        ),
    ]
