# Generated by Django 4.1.4 on 2023-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0004_remove_customuser_sifra'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sifra',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
