# Generated by Django 4.1.4 on 2023-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0005_customuser_sifra'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='votestatus',
            field=models.IntegerField(choices=[(0, 'Candidacy Phase'), (1, 'Voting Phase'), (2, 'Election Over')], default=0),
        ),
        migrations.AddField(
            model_name='election',
            name='Phase',
            field=models.IntegerField(choices=[(0, 'Candidacy Phase'), (1, 'Voting Phase'), (2, 'Election Over')], default=0),
        ),
    ]
