# Generated by Django 4.1.6 on 2023-05-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
