# Generated by Django 4.1.4 on 2023-06-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0006_customuser_votestatus_election_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='voter',
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Process.election'),
        ),
        migrations.DeleteModel(
            name='Historicalballot',
        ),
    ]
