# Generated by Django 4.1.6 on 2023-05-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0008_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
