# Generated by Django 4.2.1 on 2023-05-26 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0011_votes_historicalvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name_of_election', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalvotes',
            name='votee',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='votee',
        ),
        migrations.AddField(
            model_name='votes',
            name='votee',
            field=models.ManyToManyField(max_length=5, related_name='votee', to=settings.AUTH_USER_MODEL),
        ),
    ]
