# Generated by Django 4.2.1 on 2023-05-26 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0012_election_remove_historicalvotes_votee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='name_of_election',
        ),
        migrations.AddField(
            model_name='historicalvotes',
            name='votee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='votes',
            name='votee',
        ),
        migrations.AddField(
            model_name='votes',
            name='votee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
